version: "3.8"
services:
  php:
    image: php:7.4-fpm
    volumes:
      - ./:/public_html
    networks:
      - backend
  database:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
      - ./:/public_html
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "${DB_PORT}:3306"
  nginx:
    image: nginx:latest
    volumes:
      - ./:/public_html
      - ./docker/etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - backend
    environment:
      - NGINX_PORT=80
    ports:
      - "${HTTP_PORT}:80"
networks:
  backend:
volumes:
  db-data: